### ISSUE TITLE
websocat fails to build with OpenSSL 4.0

### ISSUE THREAD

**Issue by loqs** [vi/websocat#311]
## websocat Version

websocat HEAD https://github.com/vi/websocat/commit/d54697e2639cd7b17341e6f3903d71a55b0fda20

## System information
Arch Linux Rolling

## Describe the bug
websocat fails to build with OpenSSL 4.0.

## Additional information
Steps to reproduce:
```
$ git clone https://github.com/vi/websocat.git
$ cd websocat
$ cargo build
....
  --- stderr

  thread 'main' (2702) panicked at /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-sys-0.9.104/build/main.rs:423:5:


  This crate is only compatible with OpenSSL (version 1.0.1 through 1.1.1, or 3), or LibreSSL 2.5
  through 4.0.x, but a different version of OpenSSL was found. The build is now aborting
  due to this version mismatch.


  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
- [websocat-openssl-4.0-build-failure.log](https://github.com/user-attachments/files/30386740/websocat-openssl-4.0-build-failure.log)
- [openssl-sys 0.9.114](https://github.com/rust-openssl/rust-openssl/compare/openssl-sys-v0.9.113...openssl-sys-v0.9.114)
- [openssl 0.10.78](https://github.com/rust-openssl/rust-openssl/compare/openssl-v0.10.77...openssl-v0.10.78)

@anthraxx @pierres

**Comment by vi** [comment]
Updated locked `openssl-sys` dependency - please check if it builds with OpenSSL 4 now.

Note that `vendored_openssl` mode would still use OpenSSL 3.6.3 instead of 4.x

**Comment by loqs** [comment]
> Updated locked `openssl-sys` dependency - please check if it builds with OpenSSL 4 now.

Thank you for the fast response. The openssl crate needs to be updated as well:
```
error[E0308]: mismatched types
    --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-0.10.64/src/x509/mod.rs:1347:37
     |
1347 |             Asn1StringRef::from_ptr(data)
     |             ----------------------- ^^^^ types differ in mutability
     |             |
     |             arguments to this function are incorrect
     |
     = note: expected raw pointer `*mut ASN1_STRING`
                found raw pointer `*const ASN1_STRING`
note: associated function defined here
    --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/foreign-types-shared-0.1.1/src/lib.rs:36:15
     |
  36 |     unsafe fn from_ptr<'a>(ptr: *mut Self::CType) -> &'a Self {
     |               ^^^^^^^^

error[E0308]: mismatched types
    --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-0.10.64/src/x509/mod.rs:1360:37
     |
1360 |             Asn1ObjectRef::from_ptr(object)
     |             ----------------------- ^^^^^^ types differ in mutability
     |             |
     |             arguments to this function are incorrect
     |
     = note: expected raw pointer `*mut ASN1_OBJECT`
                found raw pointer `*const ASN1_OBJECT`
note: associated function defined here
    --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/foreign-types-shared-0.1.1/src/lib.rs:36:15
     |
  36 |     unsafe fn from_ptr<'a>(ptr: *mut Self::CType) -> &'a Self {
     |               ^^^^^^^^

error[E0308]: mismatched types
    --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-0.10.64/src/x509/mod.rs:1928:35
     |
1928 |             X509NameRef::from_ptr(name)
     |             --------------------- ^^^^ types differ in mutability
     |             |
     |             arguments to this function are incorrect
     |
     = note: expected raw pointer `*mut X509_NAME`
                found raw pointer `*const X509_NAME`
note: associated function defined here
    --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/foreign-types-shared-0.1.1/src/lib.rs:36:15
     |
  36 |     unsafe fn from_ptr<'a>(ptr: *mut Self::CType) -> &'a Self {
     |               ^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `openssl` (lib) due to 3 previous errors
```

**Comment by vi** [comment]
Updated `openssl` too.

Note: previous commit has been overwritten by a forced push.

**Comment by loqs** [comment]
Fixed by https://github.com/vi/websocat/commit/aa8fadaa212c2287067b722d4440b4f4118b39ea. Thank You.
